import { expect, test, type Page } from '@playwright/test'
import { createRequire } from 'node:module'
const require = createRequire(import.meta.url)
async function inspect(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
  await page.addScriptTag({ path: require.resolve('axe-core/axe.min.js') })
  const violations = await page.evaluate(async () => {
    const result = await (window as unknown as { axe: { run(): Promise<{ violations: { id: string; nodes: { target: string[] }[] }[] }> } }).axe.run()
    return result.violations.map(v => ({ id: v.id, targets: v.nodes.map(n => n.target) }))
  })
  expect(violations).toEqual([])
}
async function guide(page: Page, n: number) {
  for (let i = 0; i < n; i++)await page.getByRole('button', { name: 'Run the next step for me' }).click()
}
const check = (page: Page) => page.getByRole('button', { name: 'Check this task' }).click()
const next = (page: Page) => page.getByRole('button', { name: 'Next question', exact: true }).click()
test('all six questions, misconceptions, source premises, URL replay and completed review', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/?lesson=passing-an-item&v=1')
  await inspect(page)
  await page.getByRole('button', { name: /Need 3/ }).click()
  await expect(page.getByRole('status', { name: 'Handoff need' })).toContainText('unlimited memory')
  await guide(page, 3)
  await expect(page.getByRole('img', { name: /Two slots:/ }).first()).toHaveAccessibleName(/P waiting/)
  await page.getByRole('button', { name: 'C: pop(out)', exact: true }).click()
  await expect(page.getByRole('img', { name: /Two slots:/ }).first()).toHaveAccessibleName(/P notified/)
  await page.getByRole('button', { name: 'P: resume pending push(job 3)', exact: true }).click()
  await check(page)
  await expect(page.getByRole('status', { name: 'Task feedback' })).toContainText('decremented size')
  await inspect(page)
  const checkedURL = page.url()
  await next(page)
  await guide(page, 3)
  await check(page)
  await expect(page.getByRole('status', { name: 'Task feedback' })).toContainText('not_empty_')
  await inspect(page)
  await next(page)
  await expect(page.getByRole('region', { name: 'Argument ownership contract' })).toContainText('bool try_push(T value)')
  for (const answer of [/The same job:/, /Nothing: try_push throws/, /The job: std::move/]) {
    await page.getByRole('radio', { name: answer }).check()
    await check(page)
    await expect(page.getByRole('button', { name: 'Next question', exact: true })).toBeDisabled()
  }
  await page.reload()
  await expect(page.getByRole('status', { name: 'Task feedback' })).toContainText('selects Job’s move constructor')
  await page.getByRole('radio', { name: /A moved-from j:/ }).check()
  await check(page)
  await expect(page.getByRole('img', { name: /Two slots:/ }).first()).toHaveAccessibleName(/item 4, moved-from/)
  await inspect(page)
  await next(page)
  // A legal alternative: first drain one item, then close, drain, observe false,
  // and only then reject the producer. No canonical event-string grading.
  for (const name of ['C: pop(out)', 'O: close()', 'C: pop(out)', 'C: pop(out)', 'P: push(job 3)']) await page.getByRole('button', { name, exact: true }).click()
  await check(page)
  await expect(page.getByRole('status', { name: 'Task feedback' })).toContainText('Every legal ordering')
  await inspect(page)
  await next(page)
  for (const answer of [/Yes: close\(\) joined/, /Yes: close ran first/, /No: close\(\) must/]) {
    await page.getByRole('radio', { name: answer }).check()
    await check(page)
    await expect(page.getByRole('button', { name: 'Next question', exact: true })).toBeDisabled()
  }
  await page.getByRole('radio', { name: /No: C’s pending pop/ }).check()
  await check(page)
  await expect(page.getByRole('img', { name: /Two slots:/ }).first()).toHaveAccessibleName(/Undefined behaviour/)
  await inspect(page)
  await next(page)
  for (const answer of [/No: size\(\) reserved/, /No: push returns false/, /This is a data race/]) {
    await page.getByRole('radio', { name: answer }).check()
    await check(page)
    await expect(page.getByRole('heading', { name: 'Six task checks complete' })).toHaveCount(0)
  }
  await page.getByRole('radio', { name: /Yes: the other producer/ }).check()
  await check(page)
  await expect(page.getByRole('heading', { name: 'Six task checks complete' })).toBeVisible()
  await inspect(page)
  await page.getByRole('button', { name: /Make room for a sleeping producer.*press to read again/ }).click()
  await expect(page.getByText('Question 1 is checked. This view is read-only.')).toBeVisible()
  await page.getByRole('button', { name: 'Back to question 6', exact: true }).click()
  await page.goto(checkedURL)
  await expect(page.getByRole('status', { name: 'Task feedback' })).toContainText('decremented size')
  await page.getByRole('button', { name: 'Reset task' }).click()
  await page.goBack()
  await expect(page.getByRole('status', { name: 'Task feedback' })).toContainText('decremented size')
  expect(errors).toEqual([])
})

test('keyboard, reduced motion, invalid link recovery and safe lifetime repair', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/?lesson=passing-an-item&v=0&events=next')
  await expect(page.getByRole('alert')).toContainText('no old answer was counted')
  const push = page.getByRole('button', { name: 'P: push(job 1)', exact: true })
  await push.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('img', { name: /Two slots:/ }).first()).toHaveAccessibleName(/item 1/)
  expect(await page.locator('.needs-grid button').first().evaluate(node => getComputedStyle(node).transitionProperty)).toBe('none')
  await page.getByRole('button', { name: 'Reset task' }).click()
  for (const name of ['C: pop(out)', 'O: close()', 'C: resume pending pop(out)', 'P: finish all queue use', 'C: finish all queue use', 'O: join both finished users', 'O: destroy the queue']) await page.getByRole('button', { name, exact: true }).click()
  await expect(page.getByRole('group', { name: 'Simulated execution' })).toContainText('Storage destroyed')
  await expect(page.getByRole('button', { name: 'P: push(job 1)', exact: true })).toBeDisabled()
  await inspect(page)
})
